"""AgentEval arena - GitHub reporter.

Posts an arena result as a comment on the source GitHub issue. Optional
and explicit: nothing is ever posted without ``--github-comment``.
"""

from __future__ import annotations

import os

import httpx

from .results import ArenaResult


class ReportError(Exception):
    """Raised when posting to GitHub fails."""


def _token() -> str:
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN") or ""
    if not token:
        raise ReportError("GH_TOKEN (or GITHUB_TOKEN) is required to post comments")
    return token


def post_issue_comment(owner: str, repo: str, number: int, body: str) -> str:
    """Post a comment to a GitHub issue. Returns the comment URL."""
    token = _token()
    api_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{number}/comments"
    resp = httpx.post(
        api_url,
        json={"body": body},
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
        },
        timeout=30.0,
    )
    if resp.status_code >= 400:
        raise ReportError(f"GitHub API error {resp.status_code}: {resp.text[:200]}")
    return resp.json().get("html_url", api_url)


def build_comment(result: ArenaResult) -> str:
    """Render the arena summary as a GitHub comment (Markdown)."""
    lines = ["## 🏟️ AgentEval Arena Result", ""]
    lines.append(f"**Task:** {result.task[:200]}")
    lines.append(f"**Repository:** {result.repository} @ `{result.base_commit[:12]}`")
    lines.append(f"**Agents:** {', '.join(result.agents)} · **Runs:** {result.runs}")

    if result.results:
        lines.append("")
        lines.append("| Agent | State | Tests | Build | Regression | Cost | Time | Score |")
        lines.append("|-------|-------|-------|-------|------------|------|------|-------|")
        for r in sorted(result.results, key=lambda x: -(x.score.total if x.score else 0)):
            tests = f"{r.tests.passed_commands}/{r.tests.total_commands}" if r.tests and r.tests.total_commands else "-"
            build = "PASS" if (r.build and r.build.passed) else ("FAIL" if (r.build and r.build.total_commands) else "-")
            regression = str(r.regression.new_failures) if r.regression else "-"
            score = f"{r.score.total}" if r.score else "-"
            lines.append(
                f"| {r.agent} | {r.status.value} | {tests} | {build} | {regression} "
                f"| ${r.run.cost_usd:.4f} | {r.run.duration_s:.0f}s | {score} |"
            )

    winner = result.winner
    if winner:
        lines.append("")
        lines.append(f"**🏆 Winner: {winner.agent}** (score {winner.score.total})")

    lines.append("")
    lines.append(f"*Generated by [AgentEval](https://github.com/rexblade58/agenteval) "
                 f"v{result.agenteval_version}*")
    return "\n".join(lines)


__all__ = ["ReportError", "post_issue_comment", "build_comment"]
