"""AgentEval arena - winning-solution PR creation.

After an arena completes, the winner's diff can be pushed as a branch and
opened as a pull request with full evidence in the description.

Never pushes or opens PRs implicitly: this module is only invoked when the
user passes --create-pr.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Any

import httpx

from .exec import run_command
from .results import ArenaResult


class PullRequestError(Exception):
    """Raised when PR creation fails."""


def _token() -> str:
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN") or ""
    if not token:
        raise PullRequestError(
            "GH_TOKEN (or GITHUB_TOKEN) is required for --create-pr"
        )
    return token


def build_pr_body(result: ArenaResult) -> str:
    """Render the evidence block for the PR description."""
    lines = [
        "## 🤖 AgentEval Arena Result",
        "",
        f"**Task:** {result.task[:500]}",
        f"**Starting commit:** `{result.base_commit}`",
        f"**Winner:** {result.winner.agent if result.winner else 'n/a'} "
        f"(score {result.winner.score.total if result.winner else '-'})",
        f"**AgentEval version:** v{result.agenteval_version}",
        "",
    ]

    if result.results:
        lines.append("### Ranking")
        lines.append("")
        lines.append("| Agent | State | Tests | Build | Regression | Cost | Time | Score |")
        lines.append("|-------|-------|-------|-------|------------|------|------|-------|")
        for r in sorted(result.results, key=lambda x: -(x.score.total if x.score else 0)):
            tests = f"{r.tests.passed_commands}/{r.tests.total_commands}" if r.tests and r.tests.total_commands else "-"
            build = "PASS" if (r.build and r.build.passed) else ("FAIL" if (r.build and r.build.total_commands) else "-")
            regression = str(r.regression.new_failures) if r.regression else "-"
            score = f"{r.score.total}" if r.score else "-"
            lines.append(
                f"| {r.agent} | {r.status.value} | {tests} | {build} | {regression} "
                f"| ${r.run.cost_usd:.4f} | {r.run.duration_s:.0f}s | {score} |"
            )
        lines.append("")

    winner = result.winner
    if winner:
        lines.append("### Winning solution")
        lines.append("")
        lines.append(f"- **Agent:** {winner.agent}")
        lines.append(f"- **Score:** {winner.score.total}")
        lines.append(f"- **Duration:** {winner.run.duration_s:.0f}s")
        lines.append(f"- **Cost:** ${winner.run.cost_usd:.4f}")
        if winner.run.files_changed:
            lines.append(f"- **Files changed ({len(winner.run.files_changed)}):** "
                         + ", ".join(winner.run.files_changed))
        if winner.regression:
            lines.append(f"- **Regressions:** {winner.regression.new_failures} new failure(s), "
                         f"{winner.regression.tests_fixed} fixed")
        lines.append("")

    lines.append(f"*Generated by [AgentEval](https://github.com/rexblade58/agenteval) "
                 f"v{result.agenteval_version}*")
    return "\n".join(lines)


def create_winner_pr(
    result: ArenaResult,
    repo: Path,
    token: str | None = None,
    base_branch: str | None = None,
) -> str:
    """Push the winner's diff as a branch and open a PR. Returns the PR URL.

    ``repo`` must be a git repository (local source repo, or the clone used
    for remote/issue runs). The winner's captured diff is applied onto a
    fresh branch from the starting commit - the arena worktrees are not
    involved.
    """
    winner = result.winner
    if winner is None:
        raise PullRequestError("no winning solution to publish")
    if not winner.run.git_diff.strip():
        raise PullRequestError(f"winner '{winner.agent}' produced no changes")

    token = token or _token()
    remote_url = _get_remote(repo)
    owner, repo_name, base_branch = _parse_remote(remote_url, base_branch)

    branch = f"agenteval/{winner.agent}-{result.base_commit[:7]}"

    # 1. Fresh branch from the starting commit
    _git(repo, ["checkout", "-q", "-b", branch, result.base_commit])
    try:
        # 2. Apply the winner's diff
        with tempfile.NamedTemporaryFile("w", suffix=".patch", delete=False, encoding="utf-8") as fh:
            fh.write(winner.run.git_diff)
            patch_path = fh.name
        applied = _git(repo, ["apply", "--whitespace=nowarn", patch_path], check=False)
        if not applied:
            raise PullRequestError("winner diff does not apply cleanly on the base commit")
        Path(patch_path).unlink(missing_ok=True)

        # 3. Commit
        _git(repo, ["add", "-A"])
        commit_result = _git(
            repo,
            ["commit", "-q", "-m", f"{winner.agent}: {result.task[:80]}",
             "-m", f"Generated by AgentEval v{result.agenteval_version}"],
            check=False,
        )
        if not commit_result:
            raise PullRequestError("nothing to commit (diff empty after apply)")

        # 4. Push (authenticated)
        pushed = _push_branch(repo, remote_url, token, branch)
        if not pushed:
            raise PullRequestError("push failed - check GH_TOKEN permissions and branch protection")

        # 5. Open the PR
        return _create_pull_request(
            owner=owner,
            repo=repo_name,
            title=f"{winner.agent}: {result.task[:100]}",
            head=branch,
            base=base_branch,
            body=build_pr_body(result),
            token=token,
        )
    finally:
        # Return the repo to its original branch
        _git(repo, ["checkout", "-q", "-"], check=False)


def _push_branch(repo: Path, remote_url: str, token: str, branch: str) -> bool:
    """Push a branch to the remote using an authenticated URL."""
    push_url = _auth_url(remote_url, token)
    return _git(repo, ["push", push_url, branch], check=False)


def _git(repo: Path, args: list[str], check: bool = True) -> bool:
    result = run_command(["git", *args], repo, 120)
    if check and not result.ok:
        raise PullRequestError(f"git {' '.join(args[:2])} failed: {result.stderr.strip()}")
    return result.ok


def _get_remote(repo: Path) -> str:
    result = run_command(["git", "remote", "get-url", "origin"], repo, 60)
    if not result.ok:
        raise PullRequestError("repository has no 'origin' remote - cannot create a PR")
    return result.stdout.strip()


def _parse_remote(remote_url: str, base_branch: str | None) -> tuple[str, str, str]:
    """Extract owner/repo from an https or ssh remote URL."""
    url = remote_url
    if url.startswith("git@"):
        url = url.replace(":", "/").replace("git@", "https://")
    for prefix in ("https://", "http://"):
        if url.startswith(prefix):
            rest = url[len(prefix):]
            rest = rest.split("@", 1)[-1] if "@" in rest.split("/", 1)[0] else rest
            parts = rest.rstrip("/").split("/")
            if len(parts) >= 2:
                owner, repo_name = parts[-2], parts[-1].replace(".git", "")
                return owner, repo_name, base_branch or "main"
    raise PullRequestError(f"cannot parse remote URL: {remote_url}")


def _auth_url(remote_url: str, token: str) -> str:
    if remote_url.startswith("git@"):
        # git@host:owner/repo.git -> https://x-access-token:tok@host/owner/repo.git
        host_path = remote_url.split("@", 1)[1].replace(":", "/", 1)
        return f"https://x-access-token:{token}@{host_path}"
    if "://" in remote_url:
        scheme, rest = remote_url.split("://", 1)
        rest = rest.split("@", 1)[-1] if "@" in rest.split("/", 1)[0] else rest
        return f"{scheme}://x-access-token:{token}@{rest}"
    return remote_url


def _create_pull_request(
    owner: str,
    repo: str,
    title: str,
    head: str,
    base: str,
    body: str,
    token: str,
) -> str:
    resp = httpx.post(
        f"https://api.github.com/repos/{owner}/{repo}/pulls",
        json={"title": title, "head": head, "base": base, "body": body},
        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {token}"},
        timeout=30.0,
    )
    if resp.status_code >= 400:
        raise PullRequestError(f"GitHub API error {resp.status_code}: {resp.text[:300]}")
    return resp.json().get("html_url", "")


__all__ = ["PullRequestError", "build_pr_body", "create_winner_pr"]
